export const HOME_CATEGORIES = [
  {
    id: 'vegetables',
    name: 'Vegetables',
    itemCount: '150+ items',
    icon: 'fa-carrot',
    cardClass: 'bg-green-100 dark:bg-green-900 group-hover:bg-green-200 dark:group-hover:bg-green-800',
    iconClass: 'text-green-600 dark:text-green-400',
  },
  {
    id: 'fruits',
    name: 'Fruits',
    itemCount: '80+ items',
    icon: 'fa-apple-alt',
    cardClass: 'bg-red-100 dark:bg-red-900 group-hover:bg-red-200 dark:group-hover:bg-red-800',
    iconClass: 'text-red-600 dark:text-red-400',
  },
  {
    id: 'grains',
    name: 'Grains',
    itemCount: '45+ items',
    icon: 'fa-seedling',
    cardClass:
      'bg-yellow-100 dark:bg-yellow-900 group-hover:bg-yellow-200 dark:group-hover:bg-yellow-800',
    iconClass: 'text-yellow-600 dark:text-yellow-400',
  },
  {
    id: 'dairy',
    name: 'Dairy',
    itemCount: '25+ items',
    icon: 'fa-cheese',
    cardClass: 'bg-blue-100 dark:bg-blue-900 group-hover:bg-blue-200 dark:group-hover:bg-blue-800',
    iconClass: 'text-blue-600 dark:text-blue-400',
  },
  {
    id: 'honey',
    name: 'Honey',
    itemCount: '15+ items',
    icon: 'fa-jar',
    cardClass:
      'bg-purple-100 dark:bg-purple-900 group-hover:bg-purple-200 dark:group-hover:bg-purple-800',
    iconClass: 'text-purple-600 dark:text-purple-400',
  },
  {
    id: 'herbs',
    name: 'Herbs',
    itemCount: '30+ items',
    icon: 'fa-leaf',
    cardClass:
      'bg-orange-100 dark:bg-orange-900 group-hover:bg-orange-200 dark:group-hover:bg-orange-800',
    iconClass: 'text-orange-600 dark:text-orange-400',
  },
];

export const FEATURED_PRODUCTS = [
  {
    id: 'tomatoes',
    name: 'Fresh Tomatoes',
    farmer: "Rahim's Farm",
    location: 'Sylhet',
    price: 45,
    unit: '/kg',
    stock: '50kg',
    rating: 4.8,
    image:
      'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&h=300&fit=crop',
    isOrganic: true,
    isWishlisted: false,
  },
  {
    id: 'carrots',
    name: 'Fresh Carrots',
    farmer: "Shumi's Garden",
    location: 'Rangpur',
    price: 35,
    unit: '/kg',
    stock: '30kg',
    rating: 4.9,
    image:
      'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=400&h=300&fit=crop',
    isOrganic: false,
    isWishlisted: false,
  },
  {
    id: 'spinach',
    name: 'Fresh Spinach',
    farmer: "Sakib's Organics",
    location: 'Dhaka',
    price: 25,
    unit: '/kg',
    stock: '20kg',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&h=300&fit=crop',
    isOrganic: true,
    isWishlisted: true,
  },
  {
    id: 'broccoli',
    name: 'Fresh Broccoli',
    farmer: "Anika's Garden",
    location: 'Chittagong',
    price: 55,
    unit: '/kg',
    stock: '15kg',
    rating: 4.6,
    image:
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=300&fit=crop',
    isOrganic: false,
    isWishlisted: false,
  },
  {
    id: 'carrots-2',
    name: 'Fresh Carrots',
    farmer: "Shumi's Garden",
    location: 'Rangpur',
    price: 35,
    unit: '/kg',
    stock: '30kg',
    rating: 4.9,
    image:
      'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=400&h=300&fit=crop',
    isOrganic: false,
    isWishlisted: false,
  },
  {
    id: 'broccoli-2',
    name: 'Fresh Broccoli',
    farmer: "Anika's Garden",
    location: 'Chittagong',
    price: 55,
    unit: '/kg',
    stock: '15kg',
    rating: 4.6,
    image:
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=300&fit=crop',
    isOrganic: false,
    isWishlisted: false,
  },
  {
    id: 'broccoli-3',
    name: 'Fresh Broccoli',
    farmer: "Anika's Garden",
    location: 'Chittagong',
    price: 55,
    unit: '/kg',
    stock: '15kg',
    rating: 4.6,
    image:
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=300&fit=crop',
    isOrganic: false,
    isWishlisted: false,
  },
  {
    id: 'tomatoes-2',
    name: 'Fresh Tomatoes',
    farmer: "Rahim's Farm",
    location: 'Sylhet',
    price: 45,
    unit: '/kg',
    stock: '50kg',
    rating: 4.8,
    image:
      'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&h=300&fit=crop',
    isOrganic: true,
    isWishlisted: false,
  },
];

export const WHY_CHOOSE_US = [
  {
    id: 'delivery',
    title: 'Fast Delivery',
    description: 'Fresh produce delivered within 24 hours of harvest',
    icon: 'fa-truck',
  },
  {
    id: 'quality',
    title: 'Quality Guaranteed',
    description: '100% organic and pesticide-free produce',
    icon: 'fa-shield-alt',
  },
  {
    id: 'support',
    title: 'Support Local',
    description: 'Direct support to local farmers and communities',
    icon: 'fa-handshake',
  },
];
